### ISSUE TITLE
How to send keystrokes

### ISSUE THREAD

**Issue by alex-osman** [JugglerLKR/omxplayer-web-controls-php#3]
I'm looking through your code and I see you send the $command thru php but I'm having a hard time figuring out where you are writing this.  

I am trying to replicate this and I don't see what file you are writing to in order to send the command.  I can't trace the FIFO variable.

I have tried `echo "p" | /proc/{{pid}}/fd/0` to no avail.  Are you writing elsewhere?

Thanks

**Comment by mgroseman** [comment]
FIFO is defined and the file is created via setup.php, which it then puts it in a variable inside cfg.php.

It defaults to:   define('FIFO', getcwd().'/omxplayer_fifo');

BTW, you also might need the '-n' for echo so it doesn't add a newline character.  
 Example:  echo -n "p" > /var/www/XXXX/omxplayer_fifo

Hope that helps, Mike.

**Comment by alex-osman** [comment]
Yes! Thanks for your help, I'm working on virtually the same project but in Node.js
